name: generate animation

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths-ignore:
      - "github-contribution-grid-snake.svg"
      - "github-contribution-grid-snake-dark.svg"
      - "github-contribution-grid-snake.gif"
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Git config
        run: |
          git config --global user.name "${{ github.repository_owner }}"
          git config --global user.email "${{ github.repository_owner }}@users.noreply.github.com"

      - name: Generate snake files
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark
            github-contribution-grid-snake.gif?color_snake=white&color_dots=#e2908d,#8DDFE2,#e2908d,#8DDFE2,#e2908d

      - name: Commit and push generated files
        run: |
          git add github-contribution-grid-snake.svg github-contribution-grid-snake-dark.svg github-contribution-grid-snake.gif
          git commit -m "Update snake animation files" || echo "No changes to commit"
          git pull --rebase origin main
          git push
